name: Daily EPG Generator

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2:00 AM UTC
  workflow_dispatch: # Allows manual execution anytime

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Generator Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run EPG Generator
        run: python generate_epg.py

      - name: Checkout Destination Repo
        uses: actions/checkout@v4
        with:
          repository: 'kahar72/my-epg-project'
          token: ${{ secrets.DEST_REPO_PAT }}
          path: 'dest_repo'

      - name: Move file and Push to Destination Repo
        run: |
          cp custom_guide.xml.gz dest_repo/
          cd dest_repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add custom_guide.xml.gz
          git diff-index --quiet HEAD || (git commit -m "Automated EPG Update: custom_guide.xml.gz" && git push)
